{
 "title": "Broker Benchmarks",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Responders",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(nodeCount) from rsp_config",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes per Responder",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select nodeCount from rsp_config",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select nodeCount from rsp_config",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Update Interval",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select autoIncMs from rsp_config where autoInc > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Multi-Updates",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(autoInc) from rsp_config where collateUpdates='true'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requesters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(distinct(linkId)) from req_config",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Subs per Requester",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(pathId)/count(distinct(linkId)) from req_config where subscribe='true'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(pathId) from req_config where subscribe='true'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Invoke Interval",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select timeoutMs*invokes from req_config",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 }, "content": "# Estimated:" },
  {
   "title": "Subscribed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(distinct(pathId)) from req_config where subscribe='true'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Invokes per minute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "format": "opm",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(pathId)*60000*mean(invokes)/mean(timeoutMs) from req_config",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OUT Updates per minute",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "format": "opm",
   "valueName": "avg",
   "targets": [
    {
     "alias": "invokeUpdatesPerMin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(pathId)*60000*mean(invokes)/mean(timeoutMs) from req_config fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "autoIncUpdatesPerBatch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(distinct(pathId)) from req_config fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "autoIncInterval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(autoIncMs) from rsp_config fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "autoInc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(autoInc) from rsp_config fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IN Updates per minute",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "format": "opm",
   "valueName": "avg",
   "targets": [
    {
     "alias": "invokeUpdatesPerBatch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(*) from (select count(dummy)*count(dummy)*mean(invokes) from req_config group by path) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "autoIncUpdatesPerBatch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(pathId) from req_config fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "autoIncInterval",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(autoIncMs) from rsp_config fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "timeoutMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(timeoutMs) from req_config fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "autoInc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(autoInc) from rsp_config fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 }, "content": "# Actual:" },
  {
   "title": "Subscribed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "query": "select sum(subs) from request where inbound='true'",
     "select": [
      [
       { "params": [ "reqs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "method", "operator": "=", "value": "invoke" }
     ]
    }
   ]
  },
  {
   "title": "Invokes per minute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "format": "opm",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "query": "select sum(reqs) from request where inbound='false' and method='invoke' AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "reqs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "method", "operator": "=", "value": "invoke" }
     ]
    }
   ]
  },
  {
   "title": "OUT Updates per minute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "format": "opm",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "query": "SELECT sum(\"updates\") FROM \"message\" WHERE (\"inbound\" = 'false') AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "updates" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "IN Updates per minute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "format": "opm",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "query": "select sum(reqs) from request where inbound='false' and method='invoke' AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "updates" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Messages per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "outbound",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "query": "SELECT sum(\"requests\") + sum(\"responses\") FROM \"message\" WHERE (\"inbound\" = 'false') AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "inbound",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "query": "SELECT sum(\"requests\") + sum(\"responses\") FROM \"message\" WHERE (\"inbound\" = 'true') AND $timeFilter GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "responses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "outbound",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "query": "SELECT count(\"rid\") FROM \"request\" WHERE (\"inbound\" = 'false') AND $timeFilter GROUP BY time(10s), \"method\" fill(null)",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "inbound",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Responses per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "outbound",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "query": "SELECT count(\"rid\") FROM \"request\" WHERE (\"inbound\" = 'false') AND $timeFilter GROUP BY time(10s), \"method\" fill(null)",
     "select": [
      [
       { "params": [ "responses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "inbound",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "select": [
      [
       { "params": [ "responses" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Updates per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "outbound",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "query": "SELECT count(\"rid\") FROM \"request\" WHERE (\"inbound\" = 'false') AND $timeFilter GROUP BY time(10s), \"method\" fill(null)",
     "select": [
      [
       { "params": [ "updates" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "inbound",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "select": [
      [
       { "params": [ "updates" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Requests by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_method",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "select": [
      [
       { "params": [ "reqs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Requests by dslink",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_linkName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linkName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "select": [
      [
       { "params": [ "reqs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "outbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "query": "SELECT count(\"rid\") FROM \"request\" WHERE (\"inbound\" = 'false') AND $timeFilter GROUP BY time(10s), \"method\" fill(null)",
     "select": [
      [
       { "params": [ "errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "inbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "message",
     "select": [
      [
       { "params": [ "errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "outboundON",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "query": "SELECT sum(\"subs\") FROM \"request\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "subs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "inboundON",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "query": "SELECT sum(\"subs\") FROM \"request\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "subs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "outboundOFF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "query": "SELECT -sum(\"unsubs\") FROM \"request\" WHERE (\"inbound\" = 'false') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "unsubs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "inboundOFF",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "request",
     "query": "SELECT -sum(\"unsubs\") FROM \"request\" WHERE (\"inbound\" = 'true') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "unsubs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inbound", "operator": "=", "value": "true" }
     ]
    }
   ]
  }
 ]
}