version: '3'

services:

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      INFLUXDB_DB: dsa
    networks:
      - dsnet

  broker:
    image: iotdsa/broker-scala:0.3.1
    container_name: broker
    depends_on:
      - influxdb
    ports:
      - 9000:9000
    networks:
      - dsnet

  responder:
    image: iotdsa/broker-benchmarks
    container_name: responder
    depends_on:
      - influxdb
      - broker
    entrypoint:
      - /opt/docker/bin/benchmark-responder-app
      - -Dinflux.host=influxdb
    environment:
      broker.url: http://broker:9000/conn
      responder.count: 2
      responder.nodes: 10
      responder.autoinc.interval: 1000
    networks:
      - dsnet

  requester:
    image: iotdsa/broker-benchmarks
    container_name: requester
    depends_on:
      - influxdb
      - broker
      - responder
    entrypoint:
      - /opt/docker/bin/benchmark-requester-app
      - -Dinflux.host=influxdb
    environment:
      broker.url: http://broker:9000/conn
      requester.count: 5
      requester.batch: 10
      requester.timeout: 1000
      requester.subscribe: "true"
      rampup.delay: 200
    networks:
      - dsnet

networks:
  dsnet:
    external:
      name:  dsnet
