version: '3'

services:

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      INFLUXDB_DB: dsa
    networks:
      - dsanet

  broker:
    image: iotdsa/broker-scala:0.3.1
    container_name: broker
    depends_on:
      - influxdb
    ports:
      - 9000:9000
    networks:
      - dsanet

  responder:
    image: iotdsa/broker-benchmarks
    depends_on:
      - influxdb
      - broker
    entrypoint:
      - /opt/docker/bin/benchmark-responder-app
      - -Dinflux.host=influxdb
    environment:
      broker.url: http://broker:9000/conn
      responder.count: 10
      responder.nodes: 50
      responder.autoinc.interval: 1000
    networks:
      - dsanet

  requester:
    image: iotdsa/broker-benchmarks
    depends_on:
      - influxdb
      - broker
      - responder
    entrypoint:
      - /opt/docker/bin/benchmark-requester-app
      - -Dinflux.host=influxdb
    environment:
      broker.url: http://broker:9000/conn
      requester.count: 10
      requester.batch: 50
      requester.subscribe: "true"
    networks:
      - dsanet

networks:
  dsanet:
    external:
      name:  dsanet_local
